mark buildx >= 0.20.0 as incompatible with docker/bake-action < v6
Signed-off-by: CrazyMax <1951866+crazy-max@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,7 +32,7 @@ on:
       - 'subaction/**'
 
 env:
-  BUILDX_VERSION: latest
+  BUILDX_VERSION: v0.19.3
   BUILDKIT_IMAGE: moby/buildkit:buildx-stable-1
 
 jobs:
@@ -648,7 +648,7 @@ jobs:
       fail-fast: false
       matrix:
         buildx-version:
-          - latest
+          - v0.19.3
           - v0.14.1
     steps:
       -
@@ -720,3 +720,31 @@ jobs:
             ./test/config.hcl
           allow: network.host
           targets: app-entitlements
+
+  error-buildx-latest:
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: Checkout
+        uses: actions/checkout@v4
+      -
+        name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+        with:
+          version: v0.20.0
+      -
+        name: Build
+        id: bake
+        continue-on-error: true
+        uses: ./
+        with:
+          files: |
+            ./test/config.hcl
+      -
+        name: Check
+        run: |
+          echo "${{ toJson(steps.bake) }}"
+          if [ "${{ steps.bake.outcome }}" != "failure" ] || [ "${{ steps.bake.conclusion }}" != "success" ]; then
+            echo "::error::Should have failed"
+            exit 1
+          fi
